steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'australia-southeast1-docker.pkg.dev/sit737-23t1-mumu-4f8a866/sadia-docker-repo/sadia-image:tag1', '.' ]
images:
- 'australia-southeast1-docker.pkg.dev/sit737-23t1-mumu-4f8a866/sadia-docker-repo/sadia-image:tag1'